import './App.css';
import 'normalize.css'; // Does CSS normalization to make cross browser experience unifor
import { Helmet } from 'react-helmet';

function App() {
  return (
    <>
      <Helmet>
        {/* Site Metadata Start */}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
        <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
        <meta name="author" content="Abraham Chen"/>
        <meta name="description" content="Personal website for Abraham Chen"/>
        {/* Site Metadata End */}
        <title>Abraham Chen </title>
      </Helmet>
      <nav class="menu-wrap">
        <input type="checkbox" class="toggler" aria-label = "menu" />
        <div class="burger"><div></div></div>
        <div class="menu">
          <div>
            <div>
              <ul class="nav-links">
                <li><a class = "nav-link" href="#home">Home</a></li>
                <li><a class = "nav-link" href="#about">About</a></li>
                <li><a class = "nav-link" href="#projects">Projects</a></li>
                <li><a class = "nav-link" href="#contact">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
      <div id="content-wrap">
        <div id='home'>
          <img 
          src='portrait.png' 
          alt='Abraham, wearing glasses and a dark colored t-shirt smiles against a plain white background.'
          title="Yep, that's me!"
          className='portrait'/>
          <h1>
            <div>Glad</div>
            <div>you're</div>
            <div>here!</div>
          </h1>
        </div>
        <div id="about">
          <div className="padded-content">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
          </div>
        </div>
        <div id="projects">
          <div className="padded-content">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
          </div>
        </div>
        <div id="contact">
          <div className="padded-content-last">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste consectetur nesciunt libero esse enim similique modi delectus quaerat, beatae quas obcaecati neque? Vitae, quaerat? Assumenda, nostrum deleniti! Incidunt eligendi consectetur quidem quo veniam hic est similique veritatis in commodi expedita earum magnam deleniti quod molestias repellendus, dolor fugit minima nobis ipsa at harum non. Accusamus laboriosam architecto dolorum magnam est, aliquam, nostrum repudiandae dolor earum expedita totam maiores tenetur incidunt ex eaque qui praesentium sequi vitae reprehenderit, corrupti deserunt cumque unde asperiores. Dignissimos et architecto praesentium ullam, quas esse molestiae veritatis illum similique delectus alias, libero tempore repellendus reprehenderit hic debitis beatae distinctio, in exercitationem repellat at dolorum! Saepe libero explicabo rerum ipsa ut labore, dolor laborum veniam possimus eligendi sit est earum, totam ipsum magnam, et similique ad voluptas necessitatibus! Optio eaque laborum provident enim, doloremque omnis soluta illo aspernatur placeat laboriosam eius a quia ducimus tempore expedita. Natus eius reiciendis in repudiandae. Ea impedit eius incidunt placeat, itaque doloremque atque quasi omnis obcaecati, officiis aut doloribus earum eum asperiores enim reprehenderit, aperiam voluptatem quaerat esse dicta optio voluptatibus. Accusamus deserunt nesciunt odit a similique quidem hic veritatis temporibus nulla cumque velit voluptatibus ex in vitae consectetur, rem exercitationem ipsum? Minus quod velit praesentium saepe aut? Repellat esse alias, id molestias sed est ab fugiat eaque! Tempora repudiandae quo ex possimus impedit? Voluptas corporis repellat fugiat recusandae est sint nisi dolor iure optio totam similique labore laudantium soluta ipsum blanditiis veniam, animi culpa ad reprehenderit eaque repudiandae sunt cupiditate ratione. Necessitatibus suscipit facilis minima eaque esse sapiente non incidunt impedit eius neque et voluptatem, labore minus error accusamus, sequi voluptatum expedita harum ratione! Eos fugit, sit esse cumque amet odit ipsa, labore voluptatibus nam doloremque delectus sint, cupiditate adipisci magnam saepe? Est quam dignissimos laboriosam sed ducimus odio deleniti!
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
